#!/usr/bin/env python3
"""
SpaceFL 多智能体协作参考工作流

本脚本演示了空间联邦学习全流程多智能体协作的调用规范。
用于指导 workflow 团队各角色的工作流转。
"""

# ============================================================
# 工作流示例：10卫星LEO星座 + FedProx + 3GS对比实验
# ============================================================

# ===== Step 1: Orbit Architect 输出 =====
# 设计10颗LEO卫星，350-800km异构轨道，倾角53°
# 地面站：Beijing(1GS) / +Svalbard+Santiago(3GS) / +Singapore+Washington(5GS)

SIM_CONFIG = {
    "celestial_body": "earth",
    "atmosphere": "exponential",
    "satellites": {
        "count": 10,
        "altitudes_km": [350, 400, 450, 500, 550, 600, 650, 700, 750, 800],
        "inclination_deg": 53,
        "raan_deg": 0,
        "phase_distribution": "uniform"
    },
    "ground_stations": {
        "1gs": [{"name": "Beijing", "lat": 39.9, "lon": 116.4}],
        "3gs": [
            {"name": "Beijing", "lat": 39.9, "lon": 116.4},
            {"name": "Svalbard", "lat": 78.2, "lon": 15.5},
            {"name": "Santiago", "lat": -33.4, "lon": -70.6}
        ],
        "5gs": [
            {"name": "Beijing", "lat": 39.9, "lon": 116.4},
            {"name": "Svalbard", "lat": 78.2, "lon": 15.5},
            {"name": "Santiago", "lat": -33.4, "lon": -70.6},
            {"name": "Singapore", "lat": 1.3, "lon": 103.8},
            {"name": "Washington", "lat": 38.9, "lon": -77.0}
        ]
    },
    "backend": "kepler",
    "sim_hours": 24
}


# ===== Step 2: FL Engineer 输出 =====
# 选择 FedProx 算法，配置 MNIST+MLP
# 300轮，早停阈值90%，4个并行worker

EXPERIMENT_CONFIG = {
    "algorithm": "fedprox",
    "mu": 0.01,
    "num_rounds": 300,
    "frac_clients": 0.5,
    "batch_size": 64,
    "lr": 0.01,
    "dataset": "mnist",
    "model": "mlp",
    "num_train_workers": 4,
    "num_data_workers": 4,
    "early_stop_acc": 90.0,
    "device": "cpu"
}

# CLI command generated by FL Engineer:
CLI_CMD = (
    "fl-space experiment "
    "--sats 10 "
    "--gs 1 3 5 "
    "--rounds 300 "
    "--algo fedprox "
    "--mu 0.01 "
    "--dataset mnist "
    "--model mlp "
    "--lr 0.01 "
    "--batch-size 64 "
    "--device cpu "
    "--train-workers 4 "
    "--data-workers 4 "
    "--output output/spacefl_fedprox_gs123 "
    "--quiet"
)


# ===== Step 3: Simulation Runner 执行 =====
# 运行 CLI 命令，监控进度并收集输出文件

EXPECTED_OUTPUTS = [
    "output/spacefl_fedprox_gs123/experiment_report.json",
    "output/spacefl_fedprox_gs123/acc_curve.png",
    "output/spacefl_fedprox_gs123/contact_heatmap.png",
    "output/spacefl_fedprox_gs123/gs_map.png",
]


# ===== Step 4: Data Analyzer 分析指标 =====
ANALYSIS_METRICS = {
    "final_accuracy": None,        # 实验完成后填充
    "convergence_round": None,     # 达到early_stop_acc的轮数
    "contact_rate": None,          # 平均接触率
    "gs_impact": {
        "1gs": None,
        "3gs": None,
        "5gs": None
    },
    "baseline_comparison": None    # 与无轨道FL对比
}


# ===== Step 5: Report Generator 交付物 =====
REPORT_STRUCTURE = """
# SpaceFL 综合实验报告

## 1. 实验配置
- 项目: SpaceFL (太空联邦学习)
- 卫星: 10颗 LEO (350-800km 异构轨道)
- 地面站: 1/3/5 个 (对比实验)
- 算法: FedProx (μ=0.01)
- 数据集: MNIST (MLP模型)
- 轮次: 300 (早停阈值 90%)

## 2. 轨道设计
- [星座2D地图]
- [接触热力图]

## 3. 训练结果
- [准确率曲线]
- [损失收敛曲线]
- [时间分解图]

## 4. 对比分析
- [地面站数量对比图]
- [不同GS数下的准确率/收敛速度对比表]

## 5. 关键发现
- ...

## 6. 结论
- 最佳配置: ...
- 下一步建议: ...
"""


if __name__ == "__main__":
    print("=" * 60)
    print("SpaceFL 多智能体协作工作流 · 参考规范")
    print("=" * 60)
    print()
    print("使用方式: 通过 CodeBuddy 启动 workflow 团队")
    print()
    print("支持的智能体:")
    print("  1. orbit-architect  — 轨道架构师")
    print("  2. fl-engineer      — FL工程师")
    print("  3. simulation-runner— 仿真运维")
    print("  4. data-analyzer    — 数据分析师")
    print("  5. report-generator — 报告生成师")
    print()
    print("启动示例:")
    print('  "创建 spacefl-workflow 团队，')
    print('   我要做一个10颗LEO卫星 + FedProx + 1/3/5 GS对比实验"')
